#!/usr/bin/env bash
#
# Usage: package-file [<dir>]
# Summary: Detect the package.json that sets the current nodenv version
# Options:
#   <dir>    Directory from which to find package.json
#            [default: ${NODENV_DIR:-PWD}]

set -e
[ -n "$NODENV_DEBUG" ] && set -x

target_dir="$1"

find_package_json() {
  local package_json root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    package_json="$root/package.json"

    if [ -f "$package_json" ] && [ -s "$package_json" ]; then
      echo "$package_json"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_package_json "$target_dir"
else
  find_package_json "$NODENV_DIR" || {
    [ "$NODENV_DIR" != "$PWD" ] && find_package_json "$PWD"
  }
fi
