name: Release
on: { push: { tags: 'v[0-9]+.[0-9]+.[0-9]+' } }

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with: { egress-policy: audit }
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with: { fetch-depth: 0 }
      - run: npm run -s relnotes | tee relnotes.txt
      - uses: jasonkarns/create-release@9249b73e127bea00eb6f2caa7244657983df0557 # master
        with: { body_path: relnotes.txt }

  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with: { egress-policy: audit }
      - uses: mislav/bump-homebrew-formula-action@8e2baa47daaa8db10fcdeb04105dfa6850eb0d68 # v3.4
        with: { formula-name: nodenv }
        env:
          COMMITTER_TOKEN: ${{ secrets.BOT_TOKEN }}

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with: { egress-policy: audit }
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          scope: nodenv
          registry-url: https://registry.npmjs.org
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
